spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/demo3
    username: postgres
    password: 123456
  jpa:
    hibernate: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml